const WORD_LIST = [
  "the","be","to","of","and","a","in","that","have","it","for","not","on","with","he","as","you","do","at","this",
  "but","his","by","from","they","we","say","her","she","or","an","will","my","one","all","would","there","their",
  "what","so","up","out","if","about","who","get","which","go","me","when","make","can","like","time","no","just",
  "him","know","take","people","into","year","your","good","some","could","them","see","other","than","then","now",
  "look","only","come","its","over","think","also","back","after","use","two","how","our","work","first","well","way",
  "even","new","want","because","any","these","give","day","most","us","great","between","need","large","often","hand",
  "high","place","hold","real","life","few","north","open","seem","together","next","white","children","begin","got",
  "walk","example","ease","paper","group","always","music","those","both","mark","book","letter","until","mile","river",
  "car","feet","care","second","enough","plain","girl","usual","young","ready","above","ever","red","list","though",
  "feel","talk","bird","soon","body","dog","family","direct","pose","leave","song","measure","door","product","black",
  "short","numeral","class","wind","question","happen","complete","ship","area","half","rock","order","fire","south",
  "problem","piece","told","knew","pass","since","top","whole","king","space","heard","best","hour","better","during",
  "blue","red","map","far","eye","land","found","island","create","deep","story","cut","record","game","force","tree",
  "city","play","small","number","off","always","move","try","kind","hand","picture","again","change","off","play",
  "spell","air","away","animal","house","point","page","letter","mother","answer","found","study","still","learn",
  "plant","cover","food","sun","four","between","state","keep","eye","never","last","let","thought","city","run",
  "light","voice","power","town","fine","drive","cold","true","face","wood","main","open","seem","begin","example",
  "stand","own","end","turn","start","show","every","whether","near","add","food","plant","earth","help","great",
  "line","girl","talk","close","might","seem","next","hard","open","example","begin","life","always","those","both",
  "paper","together","got","group","often","run","important","until","children","side","feet","car","mile",
  "night","walk","white","sea","began","grow","took","river","four","carry","state","once","book","hear","stop",
  "without","second","later","miss","idea","enough","eat","face","watch","far","indian","real","almost","let","above",
  "girl","sometimes","mountain","cut","young","talk","soon","list","song","being","leave","family","it",
  "fast","slow","jump","happy","sad","big","little","love","hate","run","sit","stand","write","read","speak",
  "listen","watch","learn","teach","build","break","fix","help","hurt","save","lose","find","hide","show",
  "tell","ask","answer","call","remember","forget","begin","end","start","stop","open","close","push","pull",
  "throw","catch","kick","hit","miss","win","fail","try","give","take","send","receive","buy","sell",
  "grow","shrink","rise","fall","fill","empty","clean","dirty","hot","cold","warm","cool","bright","dark",
  "loud","quiet","fast","slow","strong","weak","heavy","light","hard","soft","rough","smooth","sharp","dull",
  "sweet","sour","bitter","salty","fresh","stale","alive","dead","awake","asleep","busy","free","ready","done",
  "true","false","right","wrong","good","bad","better","worse","best","worst","more","less","much","many","few"
];

const AI_PARAGRAPHS = [
  "The morning sun cast long shadows across the empty street as she walked to the corner store. She had done this every day for years, but today felt different. The air smelled of rain and something else she could not quite name. A cat watched her from a window ledge, its yellow eyes tracking her movement with quiet intensity.",
  "Programming is the art of telling a machine what to do in a language it can understand. The best code is not the most clever or the most compact, but the most readable. When you write code, you write it once but others will read it many times. Clarity is kindness to your future self and to your teammates.",
  "The ocean does not care about your problems. It has been crashing against the shore for millions of years and will continue long after every human concern has faded into history. Standing at the edge of the water you feel both insignificant and strangely calm. The rhythm of the waves is older than thought.",
  "Learning a new skill takes time and patience. At first everything feels slow and awkward. Your fingers hesitate before each key, your mind searches for words that should come naturally. But with practice the movements become automatic, the words flow without effort, and what once felt impossible becomes second nature.",
  "Cities are strange ecosystems. Millions of people live within a few square miles, each carrying an entire universe of thoughts, memories, and dreams. They pass each other on sidewalks without speaking, packed into trains and elevators in silence. Yet somehow these strangers form communities, neighborhoods, and a shared sense of place.",
  "The keyboard is one of the most used interfaces between human and machine. Its layout has remained largely unchanged for over a century, designed to prevent mechanical typewriters from jamming. We inherited this quirky arrangement and kept it, our fingers learning its contours until the act of typing feels as natural as writing by hand.",
  "Rain has a way of making everything feel more serious. The world slows down, people duck into doorways and cafes, conversations become more intimate. There is nowhere to be when it rains heavily enough. You are forced to pause, to watch the water run in streams along the gutter, to wait for something to change.",
  "Good writing is mostly rewriting. The first draft is just you telling yourself the story. You have to go back, cut the excess, sharpen the ideas, find the right word instead of the almost right word. Editing is where writing actually happens. The blank page is just the beginning of a much longer conversation with yourself.",
  "Technology moves faster than our ability to understand it. New tools emerge before we have learned to use the old ones properly. We adapt, we adopt, we forget what it was like before. Each generation grows up with a different baseline of normal. What feels like science fiction today will feel mundane to children not yet born.",
  "A well made cup of coffee requires attention to many small details. The temperature of the water, the grind of the beans, the timing of the pour. Miss any one of these and the result is drinkable but not remarkable. The difference between good and great is often just the willingness to care about the small things."
];
